FROM node:alpine
RUN apk update 
# RUN apk update && apk add git && apk add python make g++

WORKDIR '/app'

COPY package.json .

# To Fix Permissions for Packages
RUN npm config set unsafe-perm true

RUN npm install --force
RUN npm install -g npm@7.19.1

COPY . .

RUN chown -R node /app/node_modules

USER node

CMD ["npm", "run", "start"]

